---
- name: "Ensure gitea dataset exists"
  community.general.zfs:
    name: "{{ gitea_dataset }}"
    state: present

- name: "Ensure gitea dir has correct permissions"
  file:
    path: "{{ gitea_dir }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: u=rwx,g=,o=

- name: gitea
  docker_container:
    name: gitea
    image: gitea/gitea
    pull: true
    volumes:
      - "{{ gitea_dir }}:/data:rw"
      # Recommended by gitea as opposed to environment variable.
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    env:
      TZ: "{{ nas_timezone }}"
      # TODO fix this. I want the ids of the ansible_user
      PUID: "1000"
      PGID: "1000"
    networks:
      - name: "traefik"
    restart_policy: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.gitea.rule: "Host(`git.{{ nas_domain }}`)"
      traefik.http.routers.gitea.middlewares: "authelia@docker"
      traefik.http.routers.gitea.entrypoints: "websecure"
      traefik.http.routers.gitea.tls.certresolver: "letsencrypt"
      traefik.http.services.gitea.loadbalancer.server.port: "3000"
